pipeline {
    agent any
    tools {
        nodejs '18.7.0'
    }
    stages {
        stage("Build") {
            steps {
                sh "npm install --legacy-peer-deps"
                echo 'test'
            }
        }
    }
}